logging:
  level:
    com.springcourse: DEBUG

server:
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: '*'

misurls:
  database: "https://midatabase.com"

